// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: lottery/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Img          string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	PrizeNum     int32  `protobuf:"varint,4,opt,name=prize_num,json=prizeNum,proto3" json:"prize_num,omitempty"`
	PrizeCode    string `protobuf:"bytes,5,opt,name=prize_code,json=prizeCode,proto3" json:"prize_code,omitempty"`
	PrizeTime    uint32 `protobuf:"varint,6,opt,name=prize_time,json=prizeTime,proto3" json:"prize_time,omitempty"`
	LeftNum      int32  `protobuf:"varint,7,opt,name=left_num,json=leftNum,proto3" json:"left_num,omitempty"`
	PrizeType    uint32 `protobuf:"varint,8,opt,name=prize_type,json=prizeType,proto3" json:"prize_type,omitempty"`
	PrizePlan    string `protobuf:"bytes,9,opt,name=prize_plan,json=prizePlan,proto3" json:"prize_plan,omitempty"`
	BeginTime    int64  `protobuf:"varint,10,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime      int64  `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DisplayOrder uint32 `protobuf:"varint,12,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	SysStatus    uint32 `protobuf:"varint,13,opt,name=sys_status,json=sysStatus,proto3" json:"sys_status,omitempty"`
}

func (x *Prize) Reset() {
	*x = Prize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prize) ProtoMessage() {}

func (x *Prize) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prize.ProtoReflect.Descriptor instead.
func (*Prize) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Prize) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prize) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Prize) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Prize) GetPrizeNum() int32 {
	if x != nil {
		return x.PrizeNum
	}
	return 0
}

func (x *Prize) GetPrizeCode() string {
	if x != nil {
		return x.PrizeCode
	}
	return ""
}

func (x *Prize) GetPrizeTime() uint32 {
	if x != nil {
		return x.PrizeTime
	}
	return 0
}

func (x *Prize) GetLeftNum() int32 {
	if x != nil {
		return x.LeftNum
	}
	return 0
}

func (x *Prize) GetPrizeType() uint32 {
	if x != nil {
		return x.PrizeType
	}
	return 0
}

func (x *Prize) GetPrizePlan() string {
	if x != nil {
		return x.PrizePlan
	}
	return ""
}

func (x *Prize) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *Prize) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Prize) GetDisplayOrder() uint32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Prize) GetSysStatus() uint32 {
	if x != nil {
		return x.SysStatus
	}
	return 0
}

type AddPrizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prize *Prize `protobuf:"bytes,1,opt,name=prize,proto3" json:"prize,omitempty"`
}

func (x *AddPrizeRequest) Reset() {
	*x = AddPrizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPrizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPrizeRequest) ProtoMessage() {}

func (x *AddPrizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPrizeRequest.ProtoReflect.Descriptor instead.
func (*AddPrizeRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AddPrizeRequest) GetPrize() *Prize {
	if x != nil {
		return x.Prize
	}
	return nil
}

type AddPrizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPrizeResponse) Reset() {
	*x = AddPrizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPrizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPrizeResponse) ProtoMessage() {}

func (x *AddPrizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPrizeResponse.ProtoReflect.Descriptor instead.
func (*AddPrizeResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{2}
}

type AddPrizeListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prizes []*Prize `protobuf:"bytes,1,rep,name=prizes,proto3" json:"prizes,omitempty"`
}

func (x *AddPrizeListRequest) Reset() {
	*x = AddPrizeListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPrizeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPrizeListRequest) ProtoMessage() {}

func (x *AddPrizeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPrizeListRequest.ProtoReflect.Descriptor instead.
func (*AddPrizeListRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AddPrizeListRequest) GetPrizes() []*Prize {
	if x != nil {
		return x.Prizes
	}
	return nil
}

type AddPrizeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPrizeListResponse) Reset() {
	*x = AddPrizeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPrizeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPrizeListResponse) ProtoMessage() {}

func (x *AddPrizeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPrizeListResponse.ProtoReflect.Descriptor instead.
func (*AddPrizeListResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{4}
}

type ClearPrizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearPrizeRequest) Reset() {
	*x = ClearPrizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearPrizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPrizeRequest) ProtoMessage() {}

func (x *ClearPrizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPrizeRequest.ProtoReflect.Descriptor instead.
func (*ClearPrizeRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ClearPrizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearPrizeResponse) Reset() {
	*x = ClearPrizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearPrizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPrizeResponse) ProtoMessage() {}

func (x *ClearPrizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPrizeResponse.ProtoReflect.Descriptor instead.
func (*ClearPrizeResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{6}
}

type ImportCouponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrizeId int32  `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	Codes   string `protobuf:"bytes,2,opt,name=codes,proto3" json:"codes,omitempty"`
}

func (x *ImportCouponRequest) Reset() {
	*x = ImportCouponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCouponRequest) ProtoMessage() {}

func (x *ImportCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCouponRequest.ProtoReflect.Descriptor instead.
func (*ImportCouponRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ImportCouponRequest) GetPrizeId() int32 {
	if x != nil {
		return x.PrizeId
	}
	return 0
}

func (x *ImportCouponRequest) GetCodes() string {
	if x != nil {
		return x.Codes
	}
	return ""
}

type ImportCouponResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportCouponResponse) Reset() {
	*x = ImportCouponResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCouponResponse) ProtoMessage() {}

func (x *ImportCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCouponResponse.ProtoReflect.Descriptor instead.
func (*ImportCouponResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{8}
}

type ImportCouponWithCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrizeId int32  `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	Codes   string `protobuf:"bytes,2,opt,name=codes,proto3" json:"codes,omitempty"`
}

func (x *ImportCouponWithCacheRequest) Reset() {
	*x = ImportCouponWithCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCouponWithCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCouponWithCacheRequest) ProtoMessage() {}

func (x *ImportCouponWithCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCouponWithCacheRequest.ProtoReflect.Descriptor instead.
func (*ImportCouponWithCacheRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ImportCouponWithCacheRequest) GetPrizeId() int32 {
	if x != nil {
		return x.PrizeId
	}
	return 0
}

func (x *ImportCouponWithCacheRequest) GetCodes() string {
	if x != nil {
		return x.Codes
	}
	return ""
}

type ImportCouponWithCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportCouponWithCacheResponse) Reset() {
	*x = ImportCouponWithCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCouponWithCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCouponWithCacheResponse) ProtoMessage() {}

func (x *ImportCouponWithCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCouponWithCacheResponse.ProtoReflect.Descriptor instead.
func (*ImportCouponWithCacheResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{10}
}

type ClearCouponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearCouponRequest) Reset() {
	*x = ClearCouponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCouponRequest) ProtoMessage() {}

func (x *ClearCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCouponRequest.ProtoReflect.Descriptor instead.
func (*ClearCouponRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{11}
}

type ClearCouponResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearCouponResponse) Reset() {
	*x = ClearCouponResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCouponResponse) ProtoMessage() {}

func (x *ClearCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCouponResponse.ProtoReflect.Descriptor instead.
func (*ClearCouponResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{12}
}

type ClearLotteryTimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLotteryTimesRequest) Reset() {
	*x = ClearLotteryTimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLotteryTimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLotteryTimesRequest) ProtoMessage() {}

func (x *ClearLotteryTimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLotteryTimesRequest.ProtoReflect.Descriptor instead.
func (*ClearLotteryTimesRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{13}
}

type ClearLotteryTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLotteryTimesResponse) Reset() {
	*x = ClearLotteryTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLotteryTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLotteryTimesResponse) ProtoMessage() {}

func (x *ClearLotteryTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLotteryTimesResponse.ProtoReflect.Descriptor instead.
func (*ClearLotteryTimesResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{14}
}

type ClearResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearResultRequest) Reset() {
	*x = ClearResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResultRequest) ProtoMessage() {}

func (x *ClearResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResultRequest.ProtoReflect.Descriptor instead.
func (*ClearResultRequest) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{15}
}

type ClearResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearResultResponse) Reset() {
	*x = ClearResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lottery_v1_admin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResultResponse) ProtoMessage() {}

func (x *ClearResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_v1_admin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResultResponse.ProtoReflect.Descriptor instead.
func (*ClearResultResponse) Descriptor() ([]byte, []int) {
	return file_lottery_v1_admin_proto_rawDescGZIP(), []int{16}
}

var File_lottery_v1_admin_proto protoreflect.FileDescriptor

var file_lottery_v1_admin_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x02, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x7a,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69,
	0x7a, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x7a, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x79, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x73, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x69, 0x7a, 0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x06, 0x70, 0x72,
	0x69, 0x7a, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x13, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22,
	0x16, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x1c, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x7a, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x69, 0x7a, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x14, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x80, 0x08, 0x0a,
	0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x6a, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69,
	0x7a, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a,
	0x22, 0x10, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x64, 0x5f, 0x70, 0x72, 0x69,
	0x7a, 0x65, 0x12, 0x7b, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x69, 0x7a,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x01, 0x2a, 0x22, 0x15, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2f, 0x61, 0x64, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x72, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22,
	0x12, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x70, 0x72,
	0x69, 0x7a, 0x65, 0x12, 0x7a, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22, 0x14, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12,
	0x9b, 0x01, 0x0a, 0x15, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01,
	0x2a, 0x22, 0x1a, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x12, 0x76, 0x0a,
	0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a,
	0x22, 0x13, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x63,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x8f, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x28, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x76, 0x0a, 0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x1d, 0x50, 0x01, 0x5a, 0x19, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lottery_v1_admin_proto_rawDescOnce sync.Once
	file_lottery_v1_admin_proto_rawDescData = file_lottery_v1_admin_proto_rawDesc
)

func file_lottery_v1_admin_proto_rawDescGZIP() []byte {
	file_lottery_v1_admin_proto_rawDescOnce.Do(func() {
		file_lottery_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_lottery_v1_admin_proto_rawDescData)
	})
	return file_lottery_v1_admin_proto_rawDescData
}

var file_lottery_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lottery_v1_admin_proto_goTypes = []interface{}{
	(*Prize)(nil),                         // 0: api.lottery.v1.Prize
	(*AddPrizeRequest)(nil),               // 1: api.lottery.v1.AddPrizeRequest
	(*AddPrizeResponse)(nil),              // 2: api.lottery.v1.AddPrizeResponse
	(*AddPrizeListRequest)(nil),           // 3: api.lottery.v1.AddPrizeListRequest
	(*AddPrizeListResponse)(nil),          // 4: api.lottery.v1.AddPrizeListResponse
	(*ClearPrizeRequest)(nil),             // 5: api.lottery.v1.ClearPrizeRequest
	(*ClearPrizeResponse)(nil),            // 6: api.lottery.v1.ClearPrizeResponse
	(*ImportCouponRequest)(nil),           // 7: api.lottery.v1.ImportCouponRequest
	(*ImportCouponResponse)(nil),          // 8: api.lottery.v1.ImportCouponResponse
	(*ImportCouponWithCacheRequest)(nil),  // 9: api.lottery.v1.ImportCouponWithCacheRequest
	(*ImportCouponWithCacheResponse)(nil), // 10: api.lottery.v1.ImportCouponWithCacheResponse
	(*ClearCouponRequest)(nil),            // 11: api.lottery.v1.ClearCouponRequest
	(*ClearCouponResponse)(nil),           // 12: api.lottery.v1.ClearCouponResponse
	(*ClearLotteryTimesRequest)(nil),      // 13: api.lottery.v1.ClearLotteryTimesRequest
	(*ClearLotteryTimesResponse)(nil),     // 14: api.lottery.v1.ClearLotteryTimesResponse
	(*ClearResultRequest)(nil),            // 15: api.lottery.v1.ClearResultRequest
	(*ClearResultResponse)(nil),           // 16: api.lottery.v1.ClearResultResponse
}
var file_lottery_v1_admin_proto_depIdxs = []int32{
	0,  // 0: api.lottery.v1.AddPrizeRequest.prize:type_name -> api.lottery.v1.Prize
	0,  // 1: api.lottery.v1.AddPrizeListRequest.prizes:type_name -> api.lottery.v1.Prize
	1,  // 2: api.lottery.v1.Admin.AddPrize:input_type -> api.lottery.v1.AddPrizeRequest
	3,  // 3: api.lottery.v1.Admin.AddPrizeList:input_type -> api.lottery.v1.AddPrizeListRequest
	5,  // 4: api.lottery.v1.Admin.ClearPrize:input_type -> api.lottery.v1.ClearPrizeRequest
	7,  // 5: api.lottery.v1.Admin.ImportCoupon:input_type -> api.lottery.v1.ImportCouponRequest
	9,  // 6: api.lottery.v1.Admin.ImportCouponWithCache:input_type -> api.lottery.v1.ImportCouponWithCacheRequest
	11, // 7: api.lottery.v1.Admin.ClearCoupon:input_type -> api.lottery.v1.ClearCouponRequest
	13, // 8: api.lottery.v1.Admin.ClearLotteryTimes:input_type -> api.lottery.v1.ClearLotteryTimesRequest
	15, // 9: api.lottery.v1.Admin.ClearResult:input_type -> api.lottery.v1.ClearResultRequest
	2,  // 10: api.lottery.v1.Admin.AddPrize:output_type -> api.lottery.v1.AddPrizeResponse
	4,  // 11: api.lottery.v1.Admin.AddPrizeList:output_type -> api.lottery.v1.AddPrizeListResponse
	6,  // 12: api.lottery.v1.Admin.ClearPrize:output_type -> api.lottery.v1.ClearPrizeResponse
	8,  // 13: api.lottery.v1.Admin.ImportCoupon:output_type -> api.lottery.v1.ImportCouponResponse
	10, // 14: api.lottery.v1.Admin.ImportCouponWithCache:output_type -> api.lottery.v1.ImportCouponWithCacheResponse
	12, // 15: api.lottery.v1.Admin.ClearCoupon:output_type -> api.lottery.v1.ClearCouponResponse
	14, // 16: api.lottery.v1.Admin.ClearLotteryTimes:output_type -> api.lottery.v1.ClearLotteryTimesResponse
	16, // 17: api.lottery.v1.Admin.ClearResult:output_type -> api.lottery.v1.ClearResultResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_lottery_v1_admin_proto_init() }
func file_lottery_v1_admin_proto_init() {
	if File_lottery_v1_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lottery_v1_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPrizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPrizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPrizeListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPrizeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearPrizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearPrizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCouponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCouponResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCouponWithCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCouponWithCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCouponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCouponResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLotteryTimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLotteryTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lottery_v1_admin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lottery_v1_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_v1_admin_proto_goTypes,
		DependencyIndexes: file_lottery_v1_admin_proto_depIdxs,
		MessageInfos:      file_lottery_v1_admin_proto_msgTypes,
	}.Build()
	File_lottery_v1_admin_proto = out.File
	file_lottery_v1_admin_proto_rawDesc = nil
	file_lottery_v1_admin_proto_goTypes = nil
	file_lottery_v1_admin_proto_depIdxs = nil
}
